account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('error/', views.error, name='error'),


]

chat/urls.py

from django.urls import path, re_path
from .views import index, room, mj, mk, gold


app_name = 'chat'

urlpatterns = [
    path('1/', index, name='index'),
    path('2/', gold, name='gold'),
    path('3/', mj, name='mj'),
    path('4/', mk, name='mk'),


]

gol_boote/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from account import views as otherview

from django.views.generic import TemplateView
from django.urls import path, re_path, include
from django.contrib.auth.models import User

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', otherview.index, name='index'),
    path('about/', otherview.about, name='about'),

    path('news/',  include('news.urls', namespace='news')),
    # path('donate/',  include('donate.urls', namespace='donate')),
    path('chat/',  include('chat.urls', namespace='chat')),
    path('account/',  include('account.urls', namespace='account'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "مدیریت سایت موسسه خیریه"

news/urls.py
from django.urls import path
from . import views

app_name = 'news'


urlpatterns = [
    path('information/important/', views.news_important, name='news_important'),
    path('information/<slug:slug>/', views.news_detail, name='news_detail'),
    path('cause/<slug:slug>/', views.cause_detail, name='cause_detail'),
    path('cause/', views.cause_list, name='cause_list'),
    path('feedback/', views.feedback, name='feedback'),
    path('information/category/<slug:slug>/',
         views.news_category, name='news_category'),

    path('information/', views.news_list, name='news_list'),
]

account/models.py
from gol_boote.settings import AUTH_USER_MODEL as UserSend
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    CONFIRM_ROLE = (
        (0, "عادی"),
        (1, "مدد جو"),
        (2, "مدد کار"),
        (3, "مسئول"),
    )
    confirm_role = models.IntegerField(choices=CONFIRM_ROLE, default=0)

    img_user = models.ImageField(upload_to='profiles/', null=True, blank=True)

    JENS = (
        (0, "آقا"),
        (1, "خانوم")
    )

    ROLE = (
        (0, "مدد کار"),
        (1, "مدد جو")
    )

    role_user = models.IntegerField(choices=ROLE, default=0)

    jens_user = models.IntegerField(choices=JENS, default=0)
    comment_user = models.CharField(max_length=400, null=True, blank=True)
    address_user = models.CharField(max_length=400, null=True, blank=True)
    phone_user = models.CharField(max_length=14, null=True, blank=True)


class Group_Responsible(models.Model):
    name_group_responsible = models.CharField(max_length=100, db_index=True)
    slug_group_responsible = models.SlugField(
        max_length=200, unique=True, null=True)

    def __str__(self):
        return self.name_group_responsible


class Responsible(models.Model):
    STATUS = (
        (0, "غیر غعال"),
        (1, "فعال")
    )
    group_responsible = models.ForeignKey(
        Group_Responsible, on_delete=models.CASCADE, related_name='group')
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(
        upload_to='image_responsible/', blank=True, null=True)
    bio = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    telegram = models.CharField(max_length=100, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Feedback (models.Model):
    email = models.EmailField(null=True, blank=True)
    user = models.ForeignKey(
        UserSend, on_delete=models.CASCADE, related_name='user_send', null=True, blank=True)
    comment = models.CharField(max_length=300)

account/forms.py
from django import forms
from .models import CustomUser as User

JENS = [
    (0, "آقا"),
    (1, "خانوم")
]
ROLE = [
    (0, "مدد کار"),
    (1, "مدد جو")
]


class ImageForm(forms.Form):
    img_user = forms.ImageField(required=False, widget=forms.ClearableFileInput(
        attrs={'type': 'file', 'id': "imageUpload", 'accept': ".png, .jpg, .jpeg"}))

    username = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'class': "single-input", "autocomplete": "off", "placeholder": "نام کاربری"}))

    first_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'class': "single-input", "placeholder": "نام", "autocomplete": "off"}))

    last_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'class': "single-input", "placeholder": "نام خانوادگی", "autocomplete": "off"}))

    phone_user = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'class': "single-input", "placeholder": "شماره همراه", "autocomplete": "off"}))

    email = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'type': "email", 'class': "single-input", "placeholder": "ایمیل ", "autocomplete": "off"}))

    comment_user = forms.CharField(required=False, widget=forms.Textarea(
        attrs={'class': "single-textarea", "placeholder": "در صورت نیاز ، شرایط خود را ذکر کنید"}))

    last_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'class': "single-input", "placeholder": "نام خانوادگی"}))

    password = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={'type': "password", 'class': "single-input", "placeholder": "رمز", "autocomplete": "off"}))

    confirm = forms.CharField(max_length=100, required=False,  widget=forms.TextInput(
        attrs={'type': "password", 'class': "single-input", "placeholder": "تکرار رمز", "autocomplete": "off"}))

    address_user = forms.CharField(max_length=100,  required=False, widget=forms.TextInput(
        attrs={'class': "single-input", "placeholder": "آدرس"}))

    role_user = forms.ChoiceField(

        choices=ROLE,
    )

    jens_user = forms.ChoiceField(

        choices=JENS,
    )

account/views.py
from django.contrib.auth.decorators import login_required
from django.dispatch import receiver
from constance.signals import config_updated
from constance import config
from django.shortcuts import render, redirect
from .forms import ImageForm
from account.models import CustomUser as User
from django.contrib import auth
from news.models import News, Cause
from .models import Responsible
import json
import urllib
from django.conf import settings

from datetime import timedelta
from online_users import models as counterm
from django.contrib.auth.decorators import login_required, user_passes_test


def is_recruiter(self):
    if self.confirm_role == 1:
        return True
    else:
        return False


rec_login_required = user_passes_test(
    lambda u: True if is_recruiter(u) else False, login_url='/')


def recruiter_login_required(view_func):
    decorated_view_func = login_required(
        rec_login_required(view_func), login_url='/')
    return decorated_view_func


def login(request):
    if request.method == 'POST':
        user = auth.authenticate(
            username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('/')
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if result['success']:
                auth.login(request, user)
                return redirect('/')
            else:
                return render(request, 'login.html', {'error': 'Invalid reCAPTCHA. Please try again'})
        else:
            return render(request, 'login.html', {'error': 1})
    else:
        return render(request, 'login.html')


@recruiter_login_required
def dashboard(request):
    form = ImageForm()
    return render(request, 'dashboard.html', {'form': form})


@receiver(config_updated)
def constance_updated(sender, key, old_value, new_value, **kwargs):
    print(sender, key, old_value, new_value)


def index(request):
    
    responsible = Responsible.objects.order_by("?")[:3]
    cause = Cause.objects.order_by("?")[:3]
    news = News.objects.order_by("?")[:3]
    user_activity_objects = counterm.OnlineUserActivity.get_user_activities()
    number_of_active_users = user_activity_objects.count() + 5

    try:
        return render(request, 'index.html', {'cause': cause, 'news': news, 'config': config, 'counter': number_of_active_users, 'responsible': responsible})
    except ValueError:
        salam = {'MADAD_JOO': '20', 'MADAD_KAR': '10'}
        return render(request, 'index.html', {'cause': cause, 'news': news, 'config': salam, 'responsible': responsible})


def error(request):
    return render(request, 'error.html')


def about(request):
    responsible = Responsible.objects.order_by("?")[:9]
    user_activity_objects = counterm.OnlineUserActivity.get_user_activities()
    number_of_active_users = user_activity_objects.count() + 5

    try:
        return render(request, 'about.html', {'config': config, 'responsible': responsible, 'counter': number_of_active_users})
    except ValueError:
        salam = {'MADAD_JOO': '20', 'MADAD_KAR': '10'}
        return render(request, 'about.html', {'config': salam, 'responsible': responsible, 'counter': number_of_active_users})


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/account/login')

    else:
        return render(request, 'login.html')


def signup(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['password'] == form.cleaned_data['confirm']:
                try:
                    user = User.objects.get(
                        username=form.cleaned_data['username'])
                    form = ImageForm()
                    return render(request, 'signup.html', {'error': 'این نام کاربری در حال حاضر موجود است ، نام دیگری انتخاب کنید', 'form': form})
                except User.DoesNotExist:
                    user = User.objects.create_user(
                        form.cleaned_data['username'], img_user=form.cleaned_data['img_user'], email=form.cleaned_data['email'], password=form.cleaned_data['password'], address_user=form.cleaned_data['address_user'], first_name=form.cleaned_data['first_name'], last_name=form.cleaned_data['last_name'], phone_user=form.cleaned_data['phone_user'], comment_user=form.cleaned_data['comment_user'], role_user=form.cleaned_data['role_user'], jens_user=form.cleaned_data['jens_user'])
                    auth.login(request, user)
                    return redirect('/')
            else:
                form = ImageForm()
                return render(request, 'signup.html', {'error': 'رمز و تکرار آن یکسان نیست', 'form': form})

    else:

        form = ImageForm()

        return render(request, 'signup.html', {'form': form})

account/templates/about.html
{% extends 'base.html' %}
{% load humanize %}
{% load jformat %}
{% load staticfiles %}

{% block content %}

<div class="bradcam_area breadcam_bg overlay d-flex align-items-center justify-content-center">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3 style="font-family: myFirstFont  ">درباره ما</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- bradcam_area_end  -->



  <div class="popular_causes_area pt-120 cause_details ">
        <div class="container">
            <div class="row">
                    <div class="single_cause">
                        <div  align="right" style="font-family: myFirstFont; direction:rtl " class="causes_content">
                            <h4 style="font-family: myFirstFont;">موسسه گل بوته های امید</h4>
                            <p style="font-family: myFirstFont;">مجموعه تلاش های گروهی از انسان
                        های خیراندیش در این موسسه به صورت هدفمند، منجسم و با برخورداری از همکاری های همه جانبه نیروهای
                        دلسوز و متخصص در زمینه های روانشناسی، مددکاری اجتماعی با مجوز شماره 2668/2698/717 از سازمان
                        بهزیستی آغاز گردیده است.</p>
                            <p style="font-family: myFirstFont;">- بازتوانی و توانمند سازی روانی
                        عاطفی افراد مبتلا به بیماری ام اس و خانواده های آنان
                        <br>
                        <br>
                        - برنامه ریزی و اجرای برنامه های آموزش، راهنمایی و مشاوره در زمینه ارتقاء سطح سلامت روان افراد و
                        یاوری در زمینه بهبود بخشیدن و افزایش تاب آوری و بهینه سازی سبک زندگی در رابطه با بیماری
                        <br><br>- آگاهی رسانی اجتماعی – فرهنگی و بررسی راهکارهای مناسب در جهت هدایت حمایت های جامعه،
                        سازمان ها و نهادهای دولتی، خصوصی و داوطلب
            </p>
                            
                        </div>
                    </div>
            </div>
        </div>
    </div>



<!-- counter_area_start  -->
<div class="counter_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 mb-5 mb-lg-0">
                <div class="counter_bg overlay">
                    <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="single_counter d-flex align-items-center justify-content-center">
                                <div class="icon">
                                    <i class="flaticon-calendar"></i>
                                </div>
                                <div class="events">
                                    <h3 class="counter">{{config.MADAD_JOO}}</h3>
                                    <p align="right" style="font-family: myFirstFont; direction:rtl ">تعداد مدد جو ها
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single_counter d-flex align-items-center justify-content-center">
                                <div class="icon">
                                    <i class="flaticon-heart-beat"></i>
                                </div>
                                <div class="events">
                                    <h3 class="counter">{{config.MADAD_KAR}}</h3>
                                    <p align="right" style="font-family: myFirstFont; direction:rtl ">تعداد مدد کار ها
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single_counter d-flex align-items-center justify-content-center">
                                <div class="icon">
                                    <i class="flaticon-hug"></i>
                                </div>
                                <div class="events">
                                    <h3 >{{counter}}</h3>
                                    <p align="right" style="font-family: myFirstFont; direction:rtl ">اعضای آنلاین
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 " align="right" style=" ;  font-family: myFirstFont; direction:rtl ">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="fa fa-credit-card"></i></span>
                    <div class="media-body">
                        <h3 align="right" style=" ;  font-family: myFirstFont; direction:rtl ">۶۱۰۴-۳۳۷۷-۴۵۴۶-۱۰۰۲</h3>
                        <p align="right" style=" ;  font-family: myFirstFont; direction:rtl ">کارت ملت</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="fa fa-bank"></i></span>
                    <div class="media-body">
                        <h3 style=" ;  font-family: myFirstFont; direction:rtl "> ۵۹۳۶۶۹۵۳۵۶ </h3>
                        <p style=" ;  font-family: myFirstFont; direction:rtl ">حساب ملت</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="fa fa-credit-card"></i></span>
                    <div class="media-body">
                        <h3 align="right" style=" ;  font-family: myFirstFont; direction:rtl ">۶۲۱۹-۸۶۷۰-۰۰۰۰-۳۸۷۷</h3>
                        <p align="right" style=" ;  font-family: myFirstFont; direction:rtl "> ملت سامان</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="fa fa-bank"></i></span>
                    <div class="media-body">
                        <h3 style=" ;  font-family: myFirstFont; direction:rtl "> ۸۲۹-۸۱۹-۲۵۳۳۸۳۱-۱ </h3>
                        <p style=" ;  font-family: myFirstFont; direction:rtl ">حساب سامان</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- counter_area_end  -->

<!-- our_volunteer_area_start  -->
<div class="our_volunteer_area section_padding">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section_title text-center mb-55">
                    <h3><span align="right" style="font-family: myFirstFont; direction:rtl ">مدد کاران گل بوته</span>
                    </h3>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            {% for responsible in responsible %}

            <div class="col-lg-4 col-md-6">
                <div class="single_volenteer">
                    <div class="volenteer_thumb">
                      <a href="#">  <img height="320px" src='/media/{{responsible.image}} ' alt="">
                   </a> </div>
                    <div class="voolenteer_info d-flex align-items-end">
                        <div class="social_links">
                            <ul>
                                <li>
                            {% if responsible.telegram %}

                                    <a href="https://telegram.me/{{responsible.telegram}}"> <i class="fa fa-telegram"></i> </a>
                            {% endif %}
                                
                                </li>
                                <li>
                                
                            {% if responsible.instagram %}

                                    <a href="https://www.instagram.com/{{responsible.instagram}}"> <i class="fa fa-instagram"></i> </a>
                            {% endif %}

                                </li>
                                <li>
                                   {% if responsible.email %}

                                    <a  href="mailto:{{responsible.email}}" > <i class="fa fa-envelope-o"></i> </a>
                            {% endif %}

                                </li>
                                 </ul>
                        </div>
                        <div class="info_inner">
                            <h4 align="right" style="font-family: myFirstFont; direction:rtl ">
                                {{ responsible.name }}</h4>
                            <p align="right" style="font-family: myFirstFont; direction:rtl ">
                                {{ responsible.group_responsible }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
    
    
        </div>
    
            <div class="comment-form">
               <h4 align="right" style=" font-family: myFirstFont; direction:rtl   ">نظرات خود را ارسال کنید</h4>
               <form class="form-contact comment_form" action="{% url 'news:feedback' %}" id="commentForm" method='post'>
                  <div class="row">                    {% csrf_token %}

                     <div class="col-12">
                        <div class="form-group">
                           <textarea align="right" style=" font-family: myFirstFont; direction:rtl   "
                              class="form-control w-100" name="comment" id="comment" cols="30" rows="9"
                              placeholder="نظرات خود را بنویسید"></textarea>
                        </div>
                     </div>  
                     {% if user.is_authenticated == 0 %}

                     <div class="col-sm-12">
                        <div class="form-group">
                           <input class="form-control" align="right" style=" font-family: myFirstFont; direction:rtl   " name="email" id="email" type="email" placeholder="ایمیل">
                        </div>
                     </div>
                     {% endif %}
                  </div>
                                      <script src='https://www.google.com/recaptcha/api.js'></script>
                    <div class="g-recaptcha" data-sitekey="6Lc0zuUUAAAAAKyAbvuSCBUDrYpbTSsB_lAPotDg"></div>

                  <div class="form-group">
                     <button style=" font-family: myFirstFont; " type="submit"
                        class="button button-contactForm btn_1 boxed-btn">ارسال </button>
                  </div>
               </form>
            </div>
    </div>

</div>
<!-- our_volunteer_area_end  -->

     {% endblock %} 

account/templates/dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% load jformat %}
{% load staticfiles %}

{% block content %}

sssssssssssss
{% endblock %}

account/templates/error.html
{% extends 'base.html' %}
{% load humanize %}
{% load jformat %}
{% load staticfiles %}

{% block head %}
 <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href=" {% static '/error/normalize.min.css'%}">
<link rel="stylesheet" href=" {% static '/error/style.css'%} ">
{% endblock %}

{% block content %}

<bodyy>
	<div class="container">
		<div class="alert-box scale-in">
			<div class="alert-box--icon">
			</div>
			<div class="alert-box--content">
				<h2>اختار</h2>
				<p>ابتدا باید در سایت عضو شوید</p>
			</div>
			<div class="alert-box--button">
				<a href="#">تایید</a>
			</div>
		</div>
	</div>
</bodyy><br>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
  <script  src="{% static '/error/script.js'%} "></script>


{% endblock %}

account/templates/login.html
{% extends 'base.html' %}
{% load humanize %}
{% load jformat %}
{% load staticfiles %}


{% block head %}
 <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href=" {% static '/error/normalize.min.css'%}">
<link rel="stylesheet" href=" {% static '/error/style.css'%} ">
{% endblock %}


{% block content %}

<div class="whole-wrap">
    <div class="container ">



   
        <div align="right" style=" font-family: myFirstFont; direction:rtl" class="row">

            <div class="comment-form container">
                            <div class="bradcam_text text-center">
                            <br>
                <h4  align="right" style=" font-family: myFirstFont; direction:rtl">ورود به حساب (در صورتی که هنوز عضو
                    نشده اید <a style="font-weight: 900;" class="genric-btn success circle"
                        href="{% url 'account:signup' %}"> کلیک
                    </a> کنید)</h4>
                    </div>
                <form action="{% url 'account:login' %}" method="POST" class="form-contact comment_form"
                    id="commentForm">
                    {% csrf_token %}

                    <div id="login" class="row">

                        <div class="col-sm-6">
                            <div class="form-group">
                                <input style=" font-family: myFirstFont;" class="form-control" name="username" type="text" placeholder="نام کاربری">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">

                                <input style=" font-family: myFirstFont;" class="form-control" name="password" type="password" placeholder="رمز">
                            </div>
                        </div>
                        <div class="col-12">

                        </div>
                    </div>

                    <script src='https://www.google.com/recaptcha/api.js'></script>
                    <div class="g-recaptcha" data-sitekey="6Lc0zuUUAAAAAKyAbvuSCBUDrYpbTSsB_lAPotDg"></div>

                    <div class="form-group">

                    <br>
                        <button 
                         
 onclick="message_active('{{ error }}')"

                         align="right" style=" font-family: myFirstFont; direction:rtl" type="submit"
                            class="button button-contactForm btn_1 boxed-btn">ورود </button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

{{error}}    
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>

            if ({{error}} == 1 ) {
Swal.fire({
  icon: 'error',
  title: 'خطا',
  text: 'نام کاربری یا رمز اشتباه است!',
  footer: '<a href>آیا رمز ورود فراموش شده است ؟</a>' ,
 confirmButtonText: 'رد کردن',
})
            
            
            }
            
            
            

</script>

{% endblock  %}

account/templates/my_template.html
<h1>Welcome on {{ config.SITE_NAME }}</h1>
{% if config.BETA_LAUNCHED %}
    Woohoo! Head over <a href="/sekrit/">here</a> to use the beta.
{% else %}
    Sadly we haven't launched yet, click <a href="/newsletter/">here</a>
    to signup for our newletter.
{% endif %}