chat/urls.py

from django.urls import path, re_path
from .views import index, room, mj, mk, gold


app_name = 'chat'

urlpatterns = [
    path('1/', index, name='index'),
    path('2/', gold, name='gold'),
    path('3/', mj, name='mj'),
    path('4/', mk, name='mk'),


]

gol_boote/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from account import views as otherview

from django.views.generic import TemplateView
from django.urls import path, re_path, include
from django.contrib.auth.models import User

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', otherview.index, name='index'),
    path('about/', otherview.about, name='about'),

    path('news/',  include('news.urls', namespace='news')),
    # path('donate/',  include('donate.urls', namespace='donate')),
    path('chat/',  include('chat.urls', namespace='chat')),
    path('account/',  include('account.urls', namespace='account'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "مدیریت سایت موسسه خیریه"

chat/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    message_group = models.CharField(max_length=10, db_index=True)

    def __str__(self):
        return self.message_group


class Message(models.Model):
    author = models.ForeignKey(
        User, related_name='author_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    message_grp = models.ForeignKey(
        Group,  on_delete=models.CASCADE, related_name='message_grop', null=True, blank=True)

    def __str__(self):
        return self.author.username

    def last_10_messages(salam):
        return Message.objects.filter(message_grp=salam).order_by('-timestamp').reverse().all()[:10]

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json
import os
from account.models import Responsible
from account.models import CustomUser as User
from .decorators_role import msool_login_required, mk_login_required, mj_login_required


@login_required(login_url='/account/login/')
def room(request, room_name):
    salam = str(request.user.img_user)
    salam = "/media/" + salam
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.user.username)),
        'img_user': mark_safe(json.dumps(salam)),

    })


@login_required(login_url='/account/login/')
def index(request):
    salam = "/media/" + str(request.user.img_user)
    responsible = Responsible.objects.all()

    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(1)),
        'lname': request.user.last_name,
        'username': mark_safe(json.dumps(request.user.username)),
        'img_user': mark_safe(json.dumps(salam)),
        'responsible': responsible,

    })


@msool_login_required
def gold(request):
    salam = "/media/" + str(request.user.img_user)
    responsible = Responsible.objects.all()

    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(2)),
        'username': mark_safe(json.dumps(request.user.username)),
        'img_user': mark_safe(json.dumps(salam)),
        'responsible': responsible,

    })


@mk_login_required
def mk(request):
    salam = "/media/" + str(request.user.img_user)
    responsible = Responsible.objects.all()

    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(3)),
        'username': mark_safe(json.dumps(request.user.username)),
        'img_user': mark_safe(json.dumps(salam)),
        'responsible': responsible,

    })


@mj_login_required
def mj(request):
    salam = "/media/" + str(request.user.img_user)
    responsible = Responsible.objects.all()

    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(4)),
        'username': mark_safe(json.dumps(request.user.username)),
        'img_user': mark_safe(json.dumps(salam)),
        'responsible': responsible,

    })

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href='{% static "chat/css?family=Source+Sans+Pro:400,600,700,300"  %}' rel='stylesheet' type='text/css'>
  <script src="{% static 'chat/hoy3lrg.js' %}"></script>
  <script>try { Typekit.load({ async: true }); } catch (e) { }</script>
  <link rel='stylesheet prefetch' href="{% static 'chat/reset.min.css' %}">
  <link rel='stylesheet prefetch' href="{% static 'chat/font-awesome.min.css' %}">
  <link href="{% static 'chat/bootstrap.min.css ' %}" rel="stylesheet" id="bootstrap-css">
  <script src="{% static 'chat/bootstrap.min.js ' %}"></script>
  <script src="{% static 'chat/jquery.min.js' %}"></script>
  <link href="{% static 'chat/bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
  <script src="{% static 'chat/bootstrap.min.js ' %}"></script>
  <script src="{% static 'chat/jquery-1.11.1.min.js ' %}"></script>
  <link rel="stylesheet" href="{% static 'style.css' %}" />
</head>

<body>
  <div id="frame">
    <div id="sidepanel">
      <div id="profile">
        <div class="wrap">
          <img id="profile-img" src="{% static 'img/group.png' %}" class="online" alt="" />
          <p>{% if room_name_json == "1" %}گروه معمولی{% elif room_name_json == "2" %} گروه
            طلایی{% elif room_name_json == "3" %} گروه مدد کاران
            {% elif room_name_json == "4" %}گروه مددجویان{% endif %}</p><span style="float: right;">
            گروه مورد نظر را انتخاب کنید


          </span>
          <div id="status-options">

            <ul><a style="color: white;" href="{% url 'chat:index' %}">
                <li id="status-online"><span class="status-circle"></span>
                  <p>گروه معمولی</p>
                </li>
              </a><a style="color: white;" href="{% url 'chat:gold' %}">
                <li id="status-away"><span class="status-circle"></span>
                  <p>گروه طلایی</p>
                </li>
              </a><a style="color: white;" href="{% url 'chat:mj' %}">
                <li id="status-busy" {% if room_name_json == "3" %} class="active" {% endif %}><span
                    class="status-circle"></span>
                  <p>گروه مدد جویان</p>
                </li>
              </a>
              <a style="color: white;" href="{% url 'chat:mk' %}">
              </a>
              <li id="status-offline" {% if room_name_json == "4" %} class="active" {% endif %}><span
                  class="status-circle"></span>
                <p>گروه مدد کاران</p>
              </li>
              </a>
            </ul>
          </div>
        </div>
      </div>
      <div id="contacts">
        <ul>
          {% for responsible in responsible %}
          <li class="contact active">

            <div class="wrap">
              <a href="{% url 'index' %}"> <img src='/media/{{responsible.image}}' />
              </a>
              <div class="meta">
                <p class="name">{{ responsible.name }}</p>

                <p align="right" style="direction:rtl " class="preview">
                  {{ responsible.bio }}:

                </p>
              </div>

            </div>

          </li>

          {% endfor %}
        </ul>
      </div>
    </div>
    <div class=" content">
      <div class="contact-profile">
        <img src={{ img_user}} alt="" />
        <p>{{ lname }}</p>
        <div class="social-media">
          <a href="{% url 'index' %}">
            بازگشت به صفحه اصلی

            <img id="profile-img" src="{% static 'img/close.png' %}" class="online" alt="" />
          </a>
          <i class="fa fa-یسش" aria-hidden="true"></i>
        </div>
      </div>
      <div style="font-size:20px;" class="messages">
        <ul id="chat-log">
          {% comment %} <li class="sent">
            <img src="http://emilcarlsson.se/assets/mikeross.png" alt="" />
            <p>How the hell am I supposed to get a jury to believe you when I am not even sure that I do?!</p>
          </li>
          <li class="replies">
            <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
            <p>When you're backed against the wall, break the god damn thing down.</p>
          </li> {% endcomment %}
        </ul>
      </div>
      <div class="message-input">
        <div class="wrap">
          <input id="chat-message-input" type="text" placeholder="پیام خود را بنویسید" />
          <i class="fa fa-paperclip attachment" aria-hidden="true"></i>
          <button id="chat-message-submit" class="submit">
            <i class="fa fa-paper-plane" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </div>
  </div>

  <script src="{% static 'main.js' %}"></script>
  <script src="{% static 'reconnecting-websocket.js' %}"></script>
  <script>
    var roomName = {{ room_name_json }};
    var username = {{ username }};

    var chatSocket = new ReconnectingWebSocket(
      'ws://' + window.location.host +
      '/ws/chat/' + roomName + '/');

    chatSocket.onopen = function (e) {
      fetchMessages();
    }

    chatSocket.onmessage = function (e) {
      var data = JSON.parse(e.data);
      if (data['command'] === 'messages') {
        for (let i = 0; i < data['messages'].length; i++) {
          createMessage(data['messages'][i]);
        }
      } else if (data['command'] === 'new_message') {
        createMessage(data['message']);
      }
    };

    chatSocket.onclose = function (e) {
      console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').onkeyup = function (e) {
      if (e.keyCode === 13) {  // enter, return
        document.querySelector('#chat-message-submit').click();
      }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
      var messageInputDom = document.getElementById('chat-message-input');
      var message = messageInputDom.value;
      chatSocket.send(JSON.stringify({
        'command': 'new_message',
        'message': message,
        'from': username,
        'grp': roomName
      }));

      messageInputDom.value = '';
    };

    function fetchMessages() {
      chatSocket.send(JSON.stringify({ 'command': 'fetch_messages' }));
    }

    function createMessage(data) {
      var author = data['author'];
      var image = data['img_user'];
      var msgListTag = document.createElement('li');
      var imgTag = document.createElement('img');
      var pTag = document.createElement('p');
      pTag.textContent = data.content;
      imgTag.src = data.img_user;

      if (author === username) {
        msgListTag.className = 'sent';
      } else {
        msgListTag.className = 'replies';
      }
      msgListTag.appendChild(imgTag);
      msgListTag.appendChild(pTag);
      document.querySelector('#chat-log').appendChild(msgListTag);
    }

  </script>
</body>

</html>